# Generated by Django 3.2.11 on 2022-02-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=None)),
                ('ambient_temp', models.FloatField()),
                ('solar_irradation', models.FloatField()),
                ('module_temp', models.FloatField()),
                ('wind_speed', models.FloatField()),
            ],
        ),
    ]
