# Generated by Django 3.2.11 on 2022-02-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DCmeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=None)),
                ('DcBusVoltage', models.FloatField()),
                ('DcEnergy1', models.FloatField()),
                ('DcEnergy2', models.FloatField()),
                ('DcEnergy3', models.FloatField()),
                ('DcEnergy4', models.FloatField()),
                ('Inputcurrent1', models.FloatField()),
                ('Inputcurrent2', models.FloatField()),
                ('Inputcurrent3', models.FloatField()),
                ('Inputcurrent4', models.FloatField()),
            ],
        ),
    ]
